### ISSUE TITLE
Polish Project (Tuesday at LATEST)

### ISSUE THREAD

**Issue by Tbonexas** [Tbonexas/project2#39]
Finalize the project, double check all visuals, make sure all things function, and make sure we hit all credentials needed to complete Project 2.

**Comment by shaydaniel7** [comment]
## Application Requirements

* Must use a Node and Express server
* Must use Handlebars.js as the template engine
* Must be backed by a MySQL database with a Sequelize ORM
* Must utilize both GET and POST routes for retrieving and adding new data
* Must be deployed using Heroku (with data)
* Must utilize at least one new library, package, or technology that we haven’t discussed
* Must have a polished front end/UI
* Must have a folder structure that meets the MVC paradigm
* Must meet good quality coding standards (indentation, scoping, naming)
* Must protect API keys in Node with environment variables
